
        name: Lint Code
        on: [push, pull_request]
        jobs:
          lint:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
              - uses: actions/setup-node@v3
                with:
                  node-version: '18'
              - name: Fix Husky permissions
                run: chmod +x .husky/*
              - run: npm install
              - run: npm run lint
        